config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        pages#home
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                 edit_user GET    /users/edit(.:format)                                                                    users#edit
#                     login GET    /login(.:format)                                                                         session#new
#                           POST   /login(.:format)                                                                         session#create
#                           DELETE /login(.:format)                                                                         session#destroy
#                           GET    /users/:id(.:format)                                                                     users#show
#         animal_favourites GET    /animals/:animal_id/favourites(.:format)                                                 favourites#index
#                           POST   /animals/:animal_id/favourites(.:format)                                                 favourites#create
#      new_animal_favourite GET    /animals/:animal_id/favourites/new(.:format)                                             favourites#new
#     edit_animal_favourite GET    /animals/:animal_id/favourites/:id/edit(.:format)                                        favourites#edit
#          animal_favourite GET    /animals/:animal_id/favourites/:id(.:format)                                             favourites#show
#                           PATCH  /animals/:animal_id/favourites/:id(.:format)                                             favourites#update
#                           PUT    /animals/:animal_id/favourites/:id(.:format)                                             favourites#update
#                           DELETE /animals/:animal_id/favourites/:id(.:format)                                             favourites#destroy
#                   animals GET    /animals(.:format)                                                                       animals#index
#                           POST   /animals(.:format)                                                                       animals#create
#                new_animal GET    /animals/new(.:format)                                                                   animals#new
#               edit_animal GET    /animals/:id/edit(.:format)                                                              animals#edit
#                    animal GET    /animals/:id(.:format)                                                                   animals#show
#                           PATCH  /animals/:id(.:format)                                                                   animals#update
#                           PUT    /animals/:id(.:format)                                                                   animals#update
#                           DELETE /animals/:id(.:format)                                                                   animals#destroy
#                categories GET    /categories(.:format)                                                                    categories#index
#                           POST   /categories(.:format)                                                                    categories#create
#              new_category GET    /categories/new(.:format)                                                                categories#new
#             edit_category GET    /categories/:id/edit(.:format)                                                           categories#edit
#                  category GET    /categories/:id(.:format)                                                                categories#show
#                           PATCH  /categories/:id(.:format)                                                                categories#update
#                           PUT    /categories/:id(.:format)                                                                categories#update
#                           DELETE /categories/:id(.:format)                                                                categories#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do


root :to => 'pages#home'
resources :users, :only => [:new, :create, :update, :index]
get '/users/edit' => 'users#edit', :as => :edit_user
get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'
# get '/users/:id', to: 'users#show', as: 'users_show'
get 'users/:id', to: 'users#show'
resources :animals do
  resources :favourites
end
resources :categories






  # resources :categories_show_path, :path => "/Pigs"

end

app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id          :bigint           not null, primary key
#  name        :text
#  image       :text
#  age         :integer
#  story       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Animal < ApplicationRecord
  belongs_to :category, :optional => true
  has_many :favourites
  has_many :users, through: :favourites
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  
  end

  def new
    @animal = Animal.new
  end

def create
  animal = Animal.create animal_params
  if params[:file].present?
      # Then call Cloudinary's upload method, passing in the file in params
      req = Cloudinary::Uploader.upload(params[:file])
      # Using the public_id allows us to use Cloudinary's powerful image
      # transformation methods.
      animal.image = req["public_id"]
      animal.save
    end
  redirect_to animal
end

  def edit
      @animal = Animal.find params[:id]
  end

  def update
    animal = Animal.find parms[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      animal.image = req["public_id"]
    end
    animal.update animal_params
    animal.save
    redirect_to animal
end


  def show
      @animal = Animal.find params[:id]
  end


  def destroy
    animal = Animal.find params[:id]
    animal.destroy
    redirect_to animals_path
  end

  private
  def animal_params
    # Strong parameters: whitelist of sanitised input -- stuff we are happy to let the user provide us.
    params.require(:animal).permit(:name, :age, :story, :image)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :age %>
<%= f.text_field :age %>
<%= f.label :image %>
<%= f.cl_image_upload :image%>
<%= f.label :story %>
<%= f.text_field :story %>

  <%= f.submit %>
  <% end %>

app/views/animals/edit.html.erb
<h1>Edit an animal</h1>
<%= render :partial => 'form' %>

app/views/animals/index.html.erb
<!-- <div class="row justify-content-around"> -->
<div class="container">
<h1 class="anima_text">Our animals</h1>
<!-- <h1 class="anima_text">All Animals</h1> -->

<div class="card-columns">
<% @animals.each do |animal| %>

 <div class="card" style="width: 20rem;">

<%= link_to cl_image_tag(animal.image), animal, :class => "meet_anim"%>
    <div class="card-body">
    <h5 class="card-title"><%=animal.name %> </h5>
  </div>

  </div>
<% end %>

</div>

</div>

 <div class="content">

     <footer id="myFooter">
         <!-- <div class="container"> -->
             <div class="row">
                 <div class="col-sm-3">
                     <h5>Get started</h5>
                     <ul>
                         <li><a href="#">Home</a></li>
                         <li><a href="#">Sign up</a></li>
                         <li><a href="#">Downloads</a></li>
                     </ul>
                 </div>
                 <div class="col-sm-3">
                     <h5>About us</h5>
                     <ul>
                         <li><a href="#">Company Information</a></li>
                         <li><a href="#">Contact us</a></li>
                         <li><a href="#">Reviews</a></li>
                     </ul>
                 </div>
                 <div class="col-sm-3">
                     <h5>Support</h5>
                     <ul>
                         <li><a href="#">FAQ</a></li>
                         <li><a href="#">Help desk</a></li>
                         <li><a href="#">Forums</a></li>
                     </ul>
                 </div>
                 <div class="col-sm-3">
                     <h5>Legal</h5>
                     <ul>
                         <li><a href="#">Terms of Service</a></li>
                         <li><a href="#">Terms of Use</a></li>
                         <li><a href="#">Privacy Policy</a></li>
                     </ul>
                 </div>
             </div>
             <!-- Here we use the Google Embed API to show Google Maps. -->
             <!-- In order for this to work in your project you will need to generate a unique API key.  -->
             <iframe id="map-container" frameborder="0" style="border:0"
                 src="https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d9324800.564532317!2d-4.436619274153476!3d55.20840812097229!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e3!4m5!1s0x25a3b1142c791a9%3A0xc4f8a0433288257a!2sUK!3m2!1d55.378051!2d-3.4359729999999997!4m5!1s0x4652524a593764e1%3A0xef41abc2014c0424!2sHappy+Feet+Studio%2C+Copenhagen+NV%2C+Denmark!3m2!1d55.700316!2d12.533009!5e0!3m2!1sen!2sau!4v1564572495525!5m2!1sen!2sau" width="600" height="450" frameborder="0" style="border:0" allowfullscreen>
             </iframe>
         <!-- </div> -->
<div class="social-networks">
   <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
  <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
  <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
  </div>
  <div class="footer-copyright">
  <p>© 2016 Happy Feet Studio</p>
  </div>
  </footer>

app/views/animals/new.html.erb
<h1>Add a new animal</h1>
<%= render :partial => 'form' %>

app/views/animals/show.html.erb
<div class="container">
<h1 class="anima_text"> Meet your future pet: </h1>
<div class="row">
    <div class="col-md-8 offset-md-2">
<h1 class="anim_names"> <%= @animal.name %></h1>

<div class="imageborder">
<%= cl_image_tag @animal.image, :alt => @animal.name, :class => 'feature_animal'  %>
</div>
<ul>




   <li class="anim_stories">Age: <%= @animal.age  %> </li>
   <li class="anim_stories"> <%= @animal.story  %></li>
   <% if @animal.category.present? %>


   <div class="button1">
   <%= button_to 'favourite', animal_favourites_path(@animal), method: :post, :class => "button animated pulse infinite"%>
   </div>
   <% if @current_user.present?  %>
   <% pre_favourite = @animal.favourites.find {|favourite| favourite.user_id  == @current_user.id} %>
   <% if pre_favourite  %>
   <div class="button1">
   <%= button_to 'unfavourite', animal_favourite_path(@animal, pre_favourite), method: :delete, :class => "buttonUnfav"%>
   </div>
   </div>
   </div>
   <% end  %>

   <% end %>

   <hr>

   <li class="anim_stories">Interested in adopting <%= @animal.name %> ? </li>
     <li class="anim_stories"> Fill the form below and we will be in touch:</li>
   <form method="POST" class="message_form" action="https://formspree.io/p.kijowska@gmail.com">
   <input class="show_input" type="email" name="email" placeholder="Your email">
   <textarea name="message" placeholder="Test Message"></textarea>
   <button class="form-button" type="submit">Send</button>
 </form>
 <% end %>


 <li class="anim_stories" class="move_category">Or click to see other <%= link_to @animal.category.name, @animal.category%> </li>
</ul>

<!-- <img src="/assets/icons8.png" alt="heart"> -->
<!-- <input type="image" src="/assets/icons8-blue.png" name="heart" class="btTxtfav" id="favForm"/>
<p id="fav"></p> -->




<div class="controls">
  <% if @current_user.admin?   %>
<%= link_to "Edit animals", edit_animal_path(@animal)  %>

  <%= link_to "Delete animal", @animal, :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
<% end %>


</div>
</div>
</div>
</div>
</div>




<div class="content">
</div>
    <footer id="myFooter">
        <!-- <div class="container"> -->
            <div class="row">
                <div class="col-sm-3">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Legal</h5>
                    <ul>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <!-- Here we use the Google Embed API to show Google Maps. -->
            <!-- In order for this to work in your project you will need to generate a unique API key.  -->
            <iframe id="map-container" frameborder="0" style="border:0"
                src="https://www.google.com/maps/embed?pb=!1m28!1m12!1m3!1d9324800.564532317!2d-4.436619274153476!3d55.20840812097229!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m13!3e3!4m5!1s0x25a3b1142c791a9%3A0xc4f8a0433288257a!2sUK!3m2!1d55.378051!2d-3.4359729999999997!4m5!1s0x4652524a593764e1%3A0xef41abc2014c0424!2sHappy+Feet+Studio%2C+Copenhagen+NV%2C+Denmark!3m2!1d55.700316!2d12.533009!5e0!3m2!1sen!2sau!4v1564572495525!5m2!1sen!2sau" width="600" height="450" frameborder="0" style="border:0" allowfullscreen>
            </iframe>
        <!-- </div> -->
        <div class="social-networks">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
        </div>
        <div class="footer-copyright">
            <p>© 2016 Happy Feet Studio</p>
        </div>
    </footer>

</body>