config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        pages#home
#                     users GET    /users(.:format)                                                                         users#index
#                           POST   /users(.:format)                                                                         users#create
#                  new_user GET    /users/new(.:format)                                                                     users#new
#                      user PATCH  /users/:id(.:format)                                                                     users#update
#                           PUT    /users/:id(.:format)                                                                     users#update
#                 edit_user GET    /users/edit(.:format)                                                                    users#edit
#                     login GET    /login(.:format)                                                                         session#new
#                           POST   /login(.:format)                                                                         session#create
#                           DELETE /login(.:format)                                                                         session#destroy
#                           GET    /users/:id(.:format)                                                                     users#show
#         animal_favourites GET    /animals/:animal_id/favourites(.:format)                                                 favourites#index
#                           POST   /animals/:animal_id/favourites(.:format)                                                 favourites#create
#      new_animal_favourite GET    /animals/:animal_id/favourites/new(.:format)                                             favourites#new
#     edit_animal_favourite GET    /animals/:animal_id/favourites/:id/edit(.:format)                                        favourites#edit
#          animal_favourite GET    /animals/:animal_id/favourites/:id(.:format)                                             favourites#show
#                           PATCH  /animals/:animal_id/favourites/:id(.:format)                                             favourites#update
#                           PUT    /animals/:animal_id/favourites/:id(.:format)                                             favourites#update
#                           DELETE /animals/:animal_id/favourites/:id(.:format)                                             favourites#destroy
#                   animals GET    /animals(.:format)                                                                       animals#index
#                           POST   /animals(.:format)                                                                       animals#create
#                new_animal GET    /animals/new(.:format)                                                                   animals#new
#               edit_animal GET    /animals/:id/edit(.:format)                                                              animals#edit
#                    animal GET    /animals/:id(.:format)                                                                   animals#show
#                           PATCH  /animals/:id(.:format)                                                                   animals#update
#                           PUT    /animals/:id(.:format)                                                                   animals#update
#                           DELETE /animals/:id(.:format)                                                                   animals#destroy
#                categories GET    /categories(.:format)                                                                    categories#index
#                           POST   /categories(.:format)                                                                    categories#create
#              new_category GET    /categories/new(.:format)                                                                categories#new
#             edit_category GET    /categories/:id/edit(.:format)                                                           categories#edit
#                  category GET    /categories/:id(.:format)                                                                categories#show
#                           PATCH  /categories/:id(.:format)                                                                categories#update
#                           PUT    /categories/:id(.:format)                                                                categories#update
#                           DELETE /categories/:id(.:format)                                                                categories#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do


root :to => 'pages#home'
resources :users, :only => [:new, :create, :update, :index]
get '/users/edit' => 'users#edit', :as => :edit_user
get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'
# get '/users/:id', to: 'users#show', as: 'users_show'
get 'users/:id', to: 'users#show'
resources :animals do
  resources :favourites
end
resources :categories






  # resources :categories_show_path, :path => "/Pigs"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projec1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= cloudinary_js_config %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if @current_user.present? %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Happy Feet", root_path %><span class="sr-only">(current)</span>
      </li>


      <li class="nav-item">
        <%= link_to "Your profile", user_path(@current_user.id), :class => "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "All animals", animals_path, :class => "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "All Categories", categories_path, :class => "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Edit profile", edit_user_path, :class => "nav-link" %>
      </li>

      <li class="nav-item">
      <%= link_to "Logout #{ @current_user.email }", login_path, :method => 'delete', :class => "nav-link" %>
      </li>

    <% if @current_user.admin? %>
    <li class="nav-item">
    <%= link_to "All users", users_path, :class => "nav-link" %>
    </li>


  <% end %>
  <% else %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to "Sign up", new_user_path, :class => "nav-link" %>
      </li>

      <li class="nav-item">
      <%= link_to "Sign in", login_path, :class => "nav-link" %>
      </li>
    </ul>
    </div>
      <% end %>
</ul>
</div>
</nav>


  <body>
    <%= yield %>
  </body>
</html>